CREATE DATABASE ai_job_market;

USE ai_job_market;
SELECT * FROM AI_JOBS
LIMIT 10;

SELECT COUNT(*) AS TOTAL_RECORDS
FROM AI_JOBS;

#Which country has the highest average salary?
SELECT COUNTRY, AVG(SALARY_MAX) AS AVG_SALARY
FROM AI_JOBS
GROUP BY COUNTRY
HAVING AVG(SALARY_MAX) > (SELECT AVG(SALARY_MAX) FROM AI_JOBS);

#Which job title appears the most?
SELECT * FROM AI_JOBS;
SELECT JOB_TITLE,COUNT(JOB_TITLE) AS JOB_COUNT
FROM AI_JOBS
GROUP BY JOB_TITLE
ORDER BY JOB_COUNT DESC
LIMIT 1;

#Which industry is hiring the most?
SELECT INDUSTRY,COUNT(*) AS INDUSTRY_COUNT
FROM AI_JOBS
GROUP BY INDUSTRY
ORDER BY INDUSTRY_COUNT DESC
LIMIT 1;

#Which experience level is most common?
SELECT EXPERIENCE_LEVEL,COUNT(*) AS EXPERIENCE_COUNT
FROM AI_JOBS
GROUP BY EXPERIENCE_LEVEL
ORDER BY EXPERIENCE_COUNT DESC
LIMIT 1;